export const ADD_TO_CART = "ADD_TO_CART ";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAIL = "CREATE_CART_FAIL";
export const CREATE_CART_RESET = "CREATE_CART_RESET";

export const GET_CARTS_REQUEST = "GET_CARTS_REQUEST";
export const GET_CARTS_SUCCESS = "GET_CARTS_SUCCESS";
export const GET_CARTS_FAIL = "GET_CARTS_FAIL";

export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_SUCCESS = "CART_DETAILS_SUCCESS";
export const CART_DETAILS_FAIL = "CART_DETAILS_FAIL";

export const CART_INVITATION_REQUEST = "CART_INVITATION_REQUEST";
export const CART_INVITATION_SUCCESS = "CART_INVITATION_SUCCESS";
export const CART_INVITATION_FAIL = "CART_INVITATION_FAIL";
export const CART_INVITATION_RESET = "CART_INVITATION_RESET";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAIL = "ACCEPT_INVITATION_FAIL";
export const ACCEPT_INVITATION_RESET = "ACCEPT_INVITATION_RESET";

export const REJECT_INVITATION_REQUEST = "REJECT_INVITATION_REQUEST";
export const REJECT_INVITATION_SUCCESS = "REJECT_INVITATION_SUCCESS";
export const REJECT_INVITATION_FAIL = "REJECT_INVITATION_FAIL";
export const REJECT_INVITATION_RESET = "REJECT_INVITATION_RESET";

export const REMOVE_CART_MEMBER_REQUEST = "REMOVE_CART_MEMBER_REQUEST";
export const REMOVE_CART_MEMBER_SUCCESS = "REMOVE_CART_MEMBER_SUCCESS";
export const REMOVE_CART_MEMBER_FAIL = "REMOVE_CART_MEMBER_FAIL";
export const REMOVE_CART_MEMBER_RESET = "REMOVE_CART_MEMBER_RESET";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL";
export const ADD_PRODUCT_TO_CART_RESET = "ADD_PRODUCT_TO_CART_RESET";

export const REMOVE_PRODUCT_FROM_CART_REQUEST = "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM__CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL";
export const REMOVE_PRODUCT_FROM_CART_RESET = "REMOVE_PRODUCT_FROM_CART_RESET";

export const REMOVE_ALL_PRODUCTS_FROM_CART_REQUEST = "REMOVE_ALL_PRODUCTS_FROM_CART_REQUEST";
export const REMOVE_ALL_PRODUCTS_FROM_CART_SUCCESS = "REMOVE_ALL_PRODUCTS_FROM_CART_SUCCESS";
export const REMOVE_ALL_PRODUCTS_FROM_CART_FAIL = "REMOVE_ALL_PRODUCTS_FROM_CART_FAIL"

export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL";
export const REMOVE_CART_RESET = "REMOVE_CART_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";